export const fitnessPhrases = [
    "Every day is a choice.",
    "Results, not promises.",
    "Decide. Commit. Succeed.",
    "Make yourself proud.",
    "Sore today, strong tomorrow.",
    "Dare to be great.",
    "The only bad workout is no workout.",
    "Get a jump on your day.",
    "Convenient. Affordable.",
    "Love yourself enough to work harder.",
    "Get In. Get Fit. Get on with Life.",
    "Push harder than yesterday.",
    "Exercise your mind and body.",
    "Hustle to gain more muscle.",
    "Push yourself.",
    "Find a way or make one.",
    "The hardest part is waking up.",
    "Hustle for the muscle.",
    "Fit does not quit.",
    "Lift today, shape tomorrow.",
    "Choose us, Choose health.",
    "No pain, No gain.",
    "Making life tougher.",
    "Let’s Be FunFit.",
    "Less Fat, More Life.",
    "The joy of Right Health.",
    "Energize your Desire.",
    "Get the body you want.",
    "Look fit, feel fit.",
    "Get the flat tummy you dream of.",
    "Health is a priority here.",
    "Feel the difference.",
    "Live longer and stronger.",
    "Tame all terrors.",
    "Fit is hit.",
    "Move it and Lose it.",
    "Be part of the Elite.",
    "A healthy mind in a healthy body.",
    "Fitness is an attitude.",
    "Focus on what you lift.",
    "Muscles will suit you.",
    "Look different, feel different.",
    "Turn your fat into a fit.",
    "Fitness is the ultimate fashion.",
    "Always something happening.",
    "Be an Inspiration.",
    "Enjoy life. Get fit.",
    "Affordable.",
    "Celebrate Your Health.",
    "Changing bodies, changing lives.",
    "Everyone needs a balance in life.",
    "Dare to be great.",
    "Exercise until the body obeys.",
    "Fit for life.",
    "Get thin and win.",
    "Fitter, healthier, happier",
    "Get a jump on your day!",
    "Get in the groove.",
    "Hustle to gain more muscle.",
    "Improve yourself.",
    "Bodies of stamina & strength.",
    "In Pursuit of Good Health",
    "Forever fit, forever strong!",
    "Life’s tough. Get fit.",
    "Health & strength.",
    "The strength that shows.",
    "The quickest way to a top shape.",
    "Losing never felt so good.",
    "Fat loss is a win.",
    "Shape it up!",
    "Show off your guns.",
    "Train like a Champion.",
    "One life. Live well.",
    "Take back your body.",
    "The evolution of fitness for HER.",
    "Persist Until Something Happens.",
    "Perspire to greatness.",
    "Love your body.",
    "Fitness for everyday people.",
    "The quickest way to top shape.",
    "Turn Fat into Fit!",
    "Use it or lose it.",
    "We change lives.",
    "Willpower knows no obstacles.",
    "You can cry, just don’t be a baby.",
    "Your journey to a healthier life.",
    "You gotta be a beast.",
    "Improvement matters.",
    "Get in the gym.",
    "Find your focus.",
    "Take a deep breath here.",
    "Go beast mode.",
    "You look good in your muscles.",
    "The gym is the best drug.",
    "Become a gym rat.",
    "Sweat the whole time.",
    "Build a strong character.",
    "Great for your body.",
    "Sweating it out in the gym.",
    "The healthy way of life company.",
    "The last real gym!",
    "Where fitness comes naturally.",
    "Results, not promises.",
    "Forever fit, forever strong!",
    "Every day is a choice.",
  ];
  